# Generated by Django 3.2.5 on 2021-08-08 11:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='price',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_type', models.CharField(choices=[('m', 'montly'), ('a', 'annual'), ('l', 'life')], max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField(max_length=2000)),
                ('price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.price')),
            ],
        ),
    ]
