# Generated by Django 3.2.5 on 2021-08-08 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='price',
        ),
        migrations.DeleteModel(
            name='price',
        ),
        migrations.DeleteModel(
            name='service',
        ),
    ]
