# Generated by Django 3.2.5 on 2021-08-10 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0004_alter_price_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
