# Generated by Django 3.2.5 on 2021-08-10 14:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0008_auto_20210810_1405'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='userProfile.price'),
        ),
        migrations.AlterField(
            model_name='price',
            name='price_type',
            field=models.CharField(choices=[('m', 'Montly Plan'), ('a', 'Annual Plan'), ('l', 'Life Plan')], max_length=1),
        ),
    ]
