# Generated by Django 3.2.5 on 2021-08-17 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0009_auto_20210810_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stripe_price_id',
            field=models.CharField(default='please insert the price id from stripe dashboard', max_length=256),
        ),
    ]
