# Generated by Django 3.2.5 on 2021-08-18 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0011_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_id',
            field=models.CharField(default='subscription stripe id', max_length=256),
        ),
    ]
