# Generated by Django 3.2.5 on 2021-08-18 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0012_subscription_stripe_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateField(default='2000-01-01 00:00:00'),
        ),
    ]
