# Generated by Django 3.2.5 on 2021-08-18 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0015_auto_20210818_1701'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='period',
        ),
        migrations.AddField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default='2000-01-01'),
        ),
        migrations.AddField(
            model_name='subscription',
            name='include_trial',
            field=models.BooleanField(default=1),
        ),
    ]
