# Generated by Django 3.2.5 on 2021-08-18 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0016_auto_20210818_1852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateField(default='2000-01-01 00:00:00'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='start_date',
            field=models.DateTimeField(default='2000-01-01 00:00:00'),
        ),
    ]
