# Generated by Django 3.2.5 on 2021-08-19 10:31

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0019_auto_20210819_1026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
