# Generated by Django 3.2.5 on 2021-08-23 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0020_alter_subscription_end_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='include_trial',
            new_name='had_trial',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='price',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='start_date',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price_type',
            field=models.CharField(default='x', max_length=2),
        ),
    ]
