# Generated by Django 3.2.5 on 2021-08-23 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0021_auto_20210823_1849'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='stripe_price_id',
        ),
        migrations.AlterField(
            model_name='subscription',
            name='had_trial',
            field=models.BooleanField(default=False),
        ),
    ]
