# Generated by Django 3.2.5 on 2021-08-28 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0022_auto_20210823_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='price_type',
        ),
        migrations.AddField(
            model_name='subscription',
            name='price',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='userProfile.price'),
        ),
    ]
