# Generated by Django 3.2.5 on 2021-08-31 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0023_auto_20210828_1234'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(default=1, max_length=256),
            preserve_default=False,
        ),
    ]
