# Generated by Django 3.2.5 on 2021-08-31 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0025_alter_profile_stripe_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='price',
            name='stripe_id',
            field=models.CharField(default='000000000000000', max_length=256),
        ),
        migrations.AddField(
            model_name='service',
            name='stripe_id',
            field=models.CharField(default='00000000000000', max_length=256),
        ),
    ]
