# Generated by Django 3.2.5 on 2021-08-31 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0026_auto_20210831_1440'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='had_trial',
        ),
        migrations.AlterField(
            model_name='price',
            name='stripe_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='service',
            name='stripe_id',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='price',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.price'),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_id',
            field=models.CharField(max_length=256),
        ),
    ]
