# Generated by Django 3.2.5 on 2021-08-31 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0027_auto_20210831_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='stripe_id',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='profile',
            name='stripe_id',
            field=models.CharField(blank=True, editable=False, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='stripe_id',
            field=models.CharField(editable=False, max_length=256),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='stripe_id',
            field=models.CharField(editable=False, max_length=256),
        ),
    ]
