# Generated by Django 3.2.5 on 2021-08-31 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0030_rename_description_service_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='service',
            old_name='content',
            new_name='description',
        ),
    ]
