# Generated by Django 3.2.5 on 2021-08-31 16:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userProfile', '0031_rename_content_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userProfile.service'),
        ),
    ]
